pause scheduled updates if open issue

diff --git a/.github/workflows/auto-update.yml b/.github/workflows/auto-update.yml
--- a/.github/workflows/auto-update.yml
+++ b/.github/workflows/auto-update.yml
@@ -4,10 +4,39 @@ on:
     - cron: '10 * * * *'
   workflow_dispatch:
 
+concurrency:
+  group: ${{ github.ref_name }}-update
+
 jobs:
+  verify:
+    name: Verify
+    runs-on: ubuntu-latest
+    # Guard against manual runs on the wrong branch
+    if: startsWith(github.ref, 'refs/heads/ver/') || startsWith(github.ref, 'refs/heads/snap/')
+    steps:
+      - name: Version Name
+        id: version
+        shell: bash
+        run: |
+          version="${GITHUB_REF_NAME##*/}"
+          formatted_version=$(echo "v${version}" | sed 's/\./_/g')
+          echo "folder_name=${version}" >> $GITHUB_OUTPUT
+      - name: Check Open Issue
+        id: test
+        shell: bash
+        run: |
+          set +e
+          gh issue list --state open --label update --json title | jq '.[].title' | cut -c2- | rev | cut -c2- | cut -d' ' -f1 | rev | grep "${{ steps.version.outputs.folder_name }}"
+          if [[ "$?" -eq "0" ]]; then
+            set -e
+            echo "::error::Will not update as an issue for the current version is still open!" && exit 1
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
   auto-update:
     name: Auto Update
     runs-on: ubuntu-latest
+    needs: verify
     steps:
       - uses: actions/checkout@v4
         with:
